org: gabrielmatukinho
app: ifmg
# https://console.aws.amazon.com/iam/home#/users
# serverless deploy --aws-profile 
# aws configure --profile 


service: ifmg-trabalho
frameworkVersion: "3.3.0"
	
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: v1
  region: sa-east-1
  profile: ifmg

functions:
  landing:
    handler: handler.handler
    events:
      - schedule: rate(5 minutes)
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
